apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.fn_api.service.ingress_hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.fn_api.service.port }}
  - host: {{ .Values.fn_lb_runner.service.ingress_hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.fn_lb_runner.service.port }}
  - host: {{ .Values.ui.service.ingress_hostname }}
    http:
      paths:
      - path: /flow
        backend:
          serviceName: {{ template "fullname" . }}-ui
          servicePort: {{ .Values.ui.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.fn.ingress.tls | indent 4 }}
  {{- end -}}
