apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}-runner
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        role: fn-runner
    spec:
      {{- if .Values.fnserver.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fnserver.nodeSelector | indent 8 }}
{{- end }}
      {{- if .Values.fnserver.tolerations }}
      tolerations:
{{ toYaml .Values.fnserver.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: fn-runner
          image: {{ .Values.fnserver.image }}:{{ .Values.fnserver.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.fnserver.resources | indent 12 }}
          securityContext:
            privileged: true
          ports:
          - containerPort: 8082
          env:
          - name: FN_IOFS_PATH
            value: "/app/data/iofs"
          - name: FN_IOFS_DOCKER_PATH
            value: "/data/iofs"
          - name: FN_NODE_TYPE
            value: "pure-runner"
          - name: FN_GRPC_PORT
            value: "9190"
          - name: FN_PORT
            value: "8082"
