apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}-runner
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        role: fn-runner
    spec:
      {{- if .Values.fn_runner.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fn_runner.nodeSelector | indent 8 }}
{{- end }}
      {{- if .Values.fn_runner.tolerations }}
      tolerations:
{{ toYaml .Values.fn_runner.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: fn-runner
          image: {{ .Values.fn_runner.image }}:{{ .Values.fn_runner.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.fn_runner.resources | indent 12 }}
          securityContext:
            privileged: true
          ports:
          - containerPort: {{ .Values.fn_runner.container_port }}
          env:
          - name: FN_IOFS_PATH
            value: "/app/data/iofs"
          - name: FN_IOFS_DOCKER_PATH
            value: "/data/iofs"
          - name: FN_NODE_TYPE
            value: "pure-runner"
          - name: FN_GRPC_PORT
            value: {{ .Values.fn_runner.grpc_port | quote }}
          - name: FN_PORT
            value: {{ .Values.fn_runner.container_port | quote }}
          - name: FN_LOG_LEVEL
            value: "DEBUG"
